version: '3'

services:
  jupyter-notebook:
    container_name: jupyter-notebook
    build:
      context: model
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=password
      - GRANT_SUDO=yes
    volumes:
      - jupyter_data:/home/jovyan/work

volumes:
  jupyter_data:
    external: false
